export const SET_SKIN = "SET_SKIN";
export const UPDATE_SKIN = "UPDATE_SKIN";
export const UPDATE_CONTACT = "UPDATE_CONTACT";
export const UPDATE_CONTACT_ERROR = "UPDATE_CONTACT_ERROR";
export const ADD_CONTACT = "ADD_CONTACT";
export const ADD_EDUCATION = "ADD_EDUCATION";
export const UPDATE_EDUCATION = "UPDATE_EDUCATION";
export const REMOVE_ERROR = 'REMOVE_ERROR';

export const SIGN_IN = "SIGN_IN";
export const SIGN_IN_FAILED = "SIGN_IN_FAILED";
export const SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS";
export const SIGN_IN_REQUEST = "SIGN_REQUEST";